### ISSUE TITLE
[SUGGESTION] Could it be possible to synchronize the items among players?

### ISSUE THREAD

**Issue by Dantoresco** [bozzobrain/LethalCompanyShipMaid#1]
Right now if you press the button to organize the items the other players don't see the items rearranged, they still see them on their original spot, I know syncing is a difficult task but the mod would be way more useful if the rearrangement was for everyone instead of local

**Comment by bozzobrain** [comment]
Still learning how this works. Let me take a look into it. Exactly the feedback I was looking for.

**Comment by bozzobrain** [comment]
This should be barely functional - the items are really not easy to get to fall to ground on clients, so I gave up on both clients and the host. I could make it so that the host has items fall to the ground and clients don't.. or ya know, actually solve the client side, but i'm tired. Feedback always welcome.

**Comment by jcsnider** [comment]
@bozzobrain - Do all clients need to have this mod in order for the sorting to sync up? It seems like when I use it no one else can see the items have moved. (Or maybe I am misunderstanding the state of this as not yet completed/not being worked on for now,  and if so I apologize.)

**Comment by bozzobrain** [comment]
@jcsnider No that is actually MY apology. It definitely needs added to the readme!

All clients must have the mod installed in order to have the updates push from the host to the clients!

Good call!
