### ISSUE TITLE
Bug: Closet organization changes with doors closed versus open.

### ISSUE THREAD

**Issue by UmaLPZ** [bozzobrain/LethalCompanyShipMaid#17]
Is the loot in the storage closet supposed to organize differently when the closet doors are open vs when they are closed? I've noticed some things move up a shelf or two when the close the closet and press the cleanup key. Then they move back if I press the key while the closet is open.

Edit: Moved the following to its own issue as you requested.
~~The mod is great but sometimes we accidentally press in the cleanup keys when typing in chat (or think we are typing in chat) and all the loot gets moved around. This might not be a big deal for most people though so it's completely understandable if it's not worth the time to implement.~~

**Comment by bozzobrain** [comment]
These are definitely two distinct issues. I'm requesting that you open a second issue with the request for the button/terminal implementation [Suggestion: Add a physical button or terminal command to cleanup the ship], as I do want to address both issues, but I want to address the storage closet more readily.

With Regards to the Storage Closet 
  -
- I personally have been waiting for feedback about the closet, as its construction is definitely a half-baked addition to the main functionality of the ship cleanup. 
- Its comical to me that this bug exists, due to the way I'm determining the location of the inside of the closet. My code determines the bounds of the storage closet by looking at the position of the left and right door and using those locations as left and right bounds. So by closing the doors, I'm guessing that this dimension changes, changing the way the objects get placed :joy:
- I have been wondering if the storage closet aspect of the mod has been used extensively by players, so that's why I'm opting to address the storage closet in this issue.
- I will look at how I am calculating the bounds and search for a better idea.
- Please provide any additional information about oddities with the storage closet or requests you have about its functionality, its time that I improve this aspect and would love feedback!
