### ISSUE TITLE
Mod freezes game

### ISSUE THREAD

**Issue by Seviper** [bozzobrain/LethalCompanyShipMaid#23]
Howdy! New to trying this mod, eager to see it working proper. 

At the current moment, using only a mod to start with more money + this one, using the default M hotkey to clean up the ship of items freezes the whole game and requires me to force-close it through windows. Here's the info involving this

- Mods involved: Shipmaid, MoreMoneyStart
- Items bought: 8 proflashlights, 4 spray paints, dropped randomly inside the ship
- Log of profile: [LogOutput.log](https://github.com/user-attachments/files/15571666/LogOutput.log)

**Comment by bozzobrain** [comment]
Since there was no object with a scrap value, I calculated the maximum scrap value as 0 and then proceded to divide by 0. 

-infinity is a bad thing to try to do in unity. 

Thanks so much for the LogOutput as that helped me find it very quickly. New release should patch this issue.

Appreciate the support!!
