### ISSUE TITLE
Enhancement Ideas

### ISSUE THREAD

**Issue by jcsnider** [bozzobrain/LethalCompanyShipMaid#3]
Couple of minor enhancement ideas, may submit a PR for these if you would be interested:

1.  Make an option to disable the items being spread out by value. This is just a user preference to keep the floor more clean with just 2 piles of large and small objects.

2. Always move whoopie cushions, or a configurable item list to to the cabinet instead of the ship floor. This is to prevent trolling with eyeless dogs. 

Really appreciate this mod, seems to work great thus far.

Edit: Do you know where we would find all of the dll references that you have in ../packages and ../dependencies if we were to want to make edits and compile ourselves? Is there a template somewhere?

**Comment by bozzobrain** [comment]
I love both of these ideas. I was already thinking about the whoopies and moving certain items to the closet.

If you follow the path of development, I have really dropped the ball on the storage closet functionality growth, so that is planned development in progress. I typically don't push 'dirty' code (although my last couple commits have been), so keep an eye out for that coming soon. 

As for the configuration or a way to Toggle functionality, this is also a work in progress.

The packages and deps are either assets of lethal company or bepinex, no template available yet. I'll document things better soon.

I really was waiting to see any traction before making things more polished, it does seem like that is a thing I should do. More soon™

**Comment by Artemis-afk** [comment]
I really like the mod.

Don`t know why u would want the bigger items deeper in the ship.
When going to the company it would be easier that big items are close to the entrance.

Still very nice and love it already ;D

**Comment by bozzobrain** [comment]
> I really like the mod.
> 
Thanks!

> Don`t know why u would want the bigger items deeper in the ship. When going to the company it would be easier that big items are close to the entrance.
> 
Completely agree, not sure why I started out this way.

> Still very nice and love it already ;D
>
Heres to hoping for continuous improvements. Keep the feedback coming.

Thank you guys for your input and let me know how you feel about the updates in V3.0.0 per your requests
